---
- name: Be sure epel repository is installed.
  yum: name=http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
  tags: epel

#- name: disable epel repository
#  ini_file: dest=/etc/yum.repos.d/epel.repo section="epel" option="enabled" value="0"
#  tags: epel
